using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;

namespace WorldNewzWebAPI.Controllers
{
    [ApiController]
    [Route("api/gemini-search")]
    public class GeminiSearchController : ControllerBase
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public GeminiSearchController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpPost]
        public async Task<IActionResult> GeminiSearch([FromBody] GeminiSearchRequest request)
        {
            if (string.IsNullOrWhiteSpace(request.Query))
            {
                return BadRequest(new { error = "Query is required" });
            }

            var apiKey = Environment.GetEnvironmentVariable("GEMINI_API_KEY");
            if (string.IsNullOrWhiteSpace(apiKey))
            {
                return StatusCode(500, new { error = "Gemini API key is not configured on the server." });
            }

            var prompt = $"Generate a comprehensive news briefing on the topic: \"{request.Query}\". " +
                         "Respond ONLY with a raw JSON object containing the following keys: " +
                         "\"headline\" (string, catchy news headline), " +
                         "\"summary\" (string, detailed 2-3 paragraph news summary/overview of the current state of this topic), " +
                         "\"takeaways\" (array of exactly 3 bullet points showing key facts/developments), " +
                         "\"context\" (string, paragraph explaining 'Why it matters'). " +
                         "Do not wrap the response in markdown code blocks like ```json. Return ONLY the raw JSON.";

            var requestBody = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = prompt }
                        }
                    }
                }
            };

            try
            {
                var client = _httpClientFactory.CreateClient();
                var url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={apiKey}";
                
                var jsonContent = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");
                var response = await client.PostAsync(url, jsonContent);
                var responseBody = await response.Content.ReadAsStringAsync();

                if (!response.IsSuccessStatusCode)
                {
                    Console.WriteLine($"⚠️ gemini-1.5-flash returned {response.StatusCode}. Retrying with gemini-pro...");
                    url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={apiKey}";
                    response = await client.PostAsync(url, jsonContent);
                    responseBody = await response.Content.ReadAsStringAsync();
                }

                if (!response.IsSuccessStatusCode)
                {
                    return StatusCode((int)response.StatusCode, new { error = "Gemini API returned an error", details = responseBody });
                }

                using var doc = JsonDocument.Parse(responseBody);
                var root = doc.RootElement;
                
                if (root.TryGetProperty("candidates", out var candidates) && 
                    candidates.ValueKind == JsonValueKind.Array && 
                    candidates.GetArrayLength() > 0)
                {
                    var candidate = candidates[0];
                    if (candidate.TryGetProperty("content", out var content) &&
                        content.TryGetProperty("parts", out var parts) &&
                        parts.ValueKind == JsonValueKind.Array &&
                        parts.GetArrayLength() > 0)
                    {
                        var text = parts[0].GetProperty("text").GetString() ?? "";
                        
                        // Clean any markdown wrapper formatting
                        text = text.Replace("```json", "").Replace("```", "").Trim();

                        try
                        {
                            using var parsedDoc = JsonDocument.Parse(text);
                            return Ok(parsedDoc.RootElement.Clone());
                        }
                        catch
                        {
                            return Ok(new { success = true, rawText = text });
                        }
                    }
                }

                return BadRequest(new { error = "No content generated by Gemini." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = "Exception during Gemini search execution", details = ex.Message });
            }
        }
    }

    public class GeminiSearchRequest
    {
        public string Query { get; set; } = string.Empty;
    }
}
