#!/bin/bash
# Quick Start Guide - After API Updates

echo "=================================================="
echo "🚀 WorldNewz API - Quick Start"
echo "=================================================="
echo ""

echo "Step 1: Stop Running Backend"
echo "   → Press Ctrl+C in your terminal"
echo ""

echo "Step 2: Clean & Rebuild"
echo "   → Run: dotnet clean"
echo "   → Run: dotnet build"
echo ""

echo "Step 3: Start Backend"
echo "   → Run: dotnet run"
echo "   → Wait for: 'Now listening on: http://localhost:5005'"
echo ""

echo "Step 4: Test Endpoints"
echo "   → Open your browser or Postman"
echo ""

echo "=================================================="
echo "📡 Available Endpoints"
echo "=================================================="
echo ""

echo "✅ Discover News:"
echo "   GET http://localhost:5005/api/news/discover"
echo ""

echo "✅ Sports News:"
echo "   GET http://localhost:5005/api/news/sports"
echo ""

echo "✅ Money/Business News:"
echo "   GET http://localhost:5005/api/money/stocks"
echo ""

echo "✅ Shopping Products:"
echo "   GET http://localhost:5005/api/shopping/products"
echo ""

echo "✅ Weather:"
echo "   GET http://localhost:5005/api/weather?city=Mumbai"
echo "   GET http://localhost:5005/api/weather?city=Delhi"
echo ""

echo "=================================================="
echo "✨ What's New"
echo "=================================================="
echo ""

echo "🆓 Free APIs (No Keys Required):"
echo "   • Saurav Tech NewsAPI - For all news categories"
echo "   • Open-Meteo - For weather data"
echo "   • FakeStore API - For shopping products"
echo ""

echo "🔒 Removed Dependencies:"
echo "   • OpenWeatherMap API key"
echo "   • NewsAPI.org key"
echo "   • YahooFinance API key"
echo ""

echo "✅ Added Features:"
echo "   • Error handling (try-catch blocks)"
echo "   • Multiple category support"
echo "   • Weather API with two-step lookup"
echo ""

echo "=================================================="
echo "📝 Frontend Integration"
echo "=================================================="
echo ""

echo "Update your frontend to call:"
echo ""
echo "const API_BASE = 'http://localhost:5005/api';"
echo ""
echo "// Discover News"
echo "fetch(\`\${API_BASE}/news/discover\`)"
echo ""
echo "// Sports News"
echo "fetch(\`\${API_BASE}/news/sports\`)"
echo ""
echo "// Money News"
echo "fetch(\`\${API_BASE}/money/stocks\`)"
echo ""
echo "// Shopping"
echo "fetch(\`\${API_BASE}/shopping/products\`)"
echo ""
echo "// Weather"
echo "fetch(\`\${API_BASE}/weather?city=Mumbai\`)"
echo ""

echo "=================================================="
echo "🎯 Troubleshooting"
echo "=================================================="
echo ""

echo "If you get errors:"
echo ""
echo "1. Clear all cache:"
echo "   → dotnet clean"
echo "   → rm -rf bin obj"
echo ""
echo "2. Rebuild:"
echo "   → dotnet restore"
echo "   → dotnet build"
echo ""
echo "3. Run with verbose logging:"
echo "   → dotnet run --verbose"
echo ""
echo "4. Check .env file location:"
echo "   → Must be in: C:\WorldNewz\WorldNewzWebAPI\backend\.env"
echo ""

echo "=================================================="
echo "✅ You're All Set!"
echo "=================================================="
echo ""
echo "All endpoints are now FREE and working!"
echo "No API keys needed. Enjoy! 🎉"
echo ""
